name: Build

on:
  release:
    types: [ created ]
  push:
    branches: [ master ]
    tags-ignore: [ 'v*' ]
  pull_request:
  workflow_dispatch:
    inputs:
      nightly:
        type: boolean
        default: true
        description: "Whether to build nightly version"
      version:
        type: string
        default: v0.0.0
        description: "Version to build (e.g. v0.0.0)"

env:
  QT_VERSION: '6.10.*'
  TARGET_NAME: 'EZ4Connect'
  DISPLAY_NAME: 'EZ4Connect'

jobs:
  build-windows-x64:
    runs-on: windows-latest
    env:
      ARCHIVE_NAME: ${{ github.event.repository.name }}-${{ github.event.release.tag_name || 'nightly' }}-windows-x64
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2022_64'
          modules: 'qt5compat qtpositioning qtwebchannel qtwebengine'
          cache: 'true'
          cache-key-prefix: 'install-qt-action-win64_msvc2022_64'

      - name: Configure
        env:
          NIGHTLY_BUILD: ${{ inputs.nightly || github.event_name != 'release' }}
          RELEASE_VERSION: ${{ inputs.version || github.event.release.tag_name }}
        run: |
          mkdir build
          if ( [bool]::Parse("${{ env.NIGHTLY_BUILD }}") ) {
            cmake -DNIGHTLY_BUILD=ON -DQT_DEBUG_FIND_PACKAGE=ON -DGIT_HASH="$(git rev-parse --short=7 HEAD)" -DCMAKE_BUILD_TYPE=Release -S . -B build
          } else {
            $VER = "${{ env.RELEASE_VERSION }}".substring(1)
            cmake -DNIGHTLY_BUILD=OFF -DREL_VER="$VER" -DCMAKE_BUILD_TYPE=Release -S . -B build
          }

      - name: Build
        run: |
          cmake --build build --target ${{ env.TARGET_NAME }} --config Release --parallel $(nproc)

      - name: Download and copy files
        env:
          VCINSTALLDIR: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC'
        run: |
          mkdir "${{ env.DISPLAY_NAME }}"
          cd "${{ env.DISPLAY_NAME }}"
          cp ../build/Release/${{ env.TARGET_NAME }}.exe .
          windeployqt.exe ${{ env.TARGET_NAME }}.exe
          curl -LO https://github.com/chenx-dust/zju-connect/releases/latest/download/zju-connect-windows-amd64.zip
          tar -xf zju-connect-windows-amd64.zip
          rm zju-connect-windows-amd64.zip
          cp ../libs/wintun/bin/amd64/wintun.dll .
          cp ../resource/qt.conf .
          rm vc_redist.x64.exe
          cd ..
          Compress-Archive -Path "${{ env.DISPLAY_NAME }}" -DestinationPath ${{ env.ARCHIVE_NAME }}.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARCHIVE_NAME }}
          path: ${{ env.ARCHIVE_NAME }}.zip

  build-windows-arm64:
    runs-on: windows-11-arm
    env:
      ARCHIVE_NAME: ${{ github.event.repository.name }}-${{ github.event.release.tag_name || 'nightly' }}-windows-arm64
    steps:
      - uses: actions/checkout@v4

      - name: Install host Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: 'windows_arm64'
          target: 'desktop'
          arch: 'win64_msvc2022_arm64'
          modules: 'qt5compat qtpositioning qtwebchannel qtwebengine'
          cache: 'true'
          cache-key-prefix: 'install-qt-action-win64_msvc2022_arm64'
          aqtsource: 'git+https://github.com/miurahr/aqtinstall.git'  # workaround for Qt6 WebEngine on Windows ARM64

      - name: Configure
        env:
          NIGHTLY_BUILD: ${{ inputs.nightly || github.event_name != 'release' }}
          RELEASE_VERSION: ${{ inputs.version || github.event.release.tag_name }}
        run: |
          mkdir build
          if ( [bool]::Parse("${{ env.NIGHTLY_BUILD }}") ) {
            cmake -DNIGHTLY_BUILD=ON -DQT_DEBUG_FIND_PACKAGE=ON -DGIT_HASH="$(git rev-parse --short=7 HEAD)" -DCMAKE_BUILD_TYPE=Release -S . -B build
          } else {
            $VER = "${{ env.RELEASE_VERSION }}".substring(1)
            cmake -DNIGHTLY_BUILD=OFF -DREL_VER="$VER" -DCMAKE_BUILD_TYPE=Release -S . -B build
          }

      - name: Build
        run: |
          cmake --build build --target ${{ env.TARGET_NAME }} --config Release --parallel $(nproc)

      - name: Download and copy files
        env:
          VCINSTALLDIR: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC'
        run: |
          mkdir "${{ env.DISPLAY_NAME }}"
          cd "${{ env.DISPLAY_NAME }}"
          cp ../build/Release/${{ env.TARGET_NAME }}.exe .
          windeployqt.exe ${{ env.TARGET_NAME }}.exe
          curl -LO https://github.com/chenx-dust/zju-connect/releases/latest/download/zju-connect-windows-arm64.zip
          tar -xf zju-connect-windows-arm64.zip
          rm zju-connect-windows-arm64.zip
          cp ../libs/wintun/bin/arm64/wintun.dll .
          cp ../resource/qt.conf .
          rm vc_redist.arm64.exe
          cd ..
          Compress-Archive -Path "${{ env.DISPLAY_NAME }}" -DestinationPath ${{ env.ARCHIVE_NAME }}.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARCHIVE_NAME }}
          path: ${{ env.ARCHIVE_NAME }}.zip

  build-macos-x64:
    runs-on: macos-14
    env:
      ARCHIVE_NAME: ${{ github.event.repository.name }}-${{ github.event.release.tag_name || 'nightly' }}-macos-x64
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: 'mac'
          target: 'desktop'
          arch: 'clang_64'
          modules: 'qt5compat qtpositioning qtwebchannel qtwebengine'
          cache: 'true'
          cache-key-prefix: 'install-qt-action-macos_clang_x64'

      - name: Configure
        env:
          NIGHTLY_BUILD: ${{ inputs.nightly || github.event_name != 'release' }}
          RELEASE_VERSION: ${{ inputs.version || github.event.release.tag_name }}
        run: |
          mkdir build
          if ${{ env.NIGHTLY_BUILD }} ; then
            cmake -DNIGHTLY_BUILD=ON -DQT_DEBUG_FIND_PACKAGE=ON -DGIT_HASH=$(git rev-parse --short=7 HEAD) -DCMAKE_OSX_ARCHITECTURES="x86_64" -S . -B build
          else
            VER=${{ env.RELEASE_VERSION }}
            cmake -DNIGHTLY_BUILD=OFF -DREL_VER=${VER#v} -DCMAKE_OSX_ARCHITECTURES="x86_64" -S . -B build
          fi

      - name: Build
        run: |
          cmake --build build --target ${{ env.TARGET_NAME }} --parallel $(nproc)

      - name: Download and copy files
        run: |
          cp -R build/${{ env.TARGET_NAME }}.app .
          curl -LO https://github.com/chenx-dust/zju-connect/releases/latest/download/zju-connect-darwin-amd64.zip
          tar -xf zju-connect-darwin-amd64.zip
          rm zju-connect-darwin-amd64.zip
          cp zju-connect ${{ env.TARGET_NAME }}.app/Contents/MacOS/
          macdeployqt ${{ env.TARGET_NAME }}.app

      - name: Package dmg file
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        run: |
          brew install create-dmg
          mkdir dmg-build
          create-dmg \
            --background ./resource/dmg-background.png \
            --window-size 430 480 \
            --app-drop-link 200 0 \
            --add-file "${{ env.DISPLAY_NAME }}.app" "./${{ env.TARGET_NAME }}.app" 0 0 \
            --add-file 修复脚本.command ./resource/macos-fix.sh 100 200 \
            --filesystem APFS \
            ${{ env.ARCHIVE_NAME }}.dmg dmg-build

      - name: Upload artifact (dmg)
        uses: actions/upload-artifact@v4
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        with:
          name: ${{ env.ARCHIVE_NAME }}
          path: ${{ env.ARCHIVE_NAME }}.dmg

      - name: Package zip file
        if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
        run: |
          zip -r ${{ env.ARCHIVE_NAME }}.zip ${{ env.TARGET_NAME }}.app

      - name: Upload artifact (zip)
        uses: actions/upload-artifact@v4
        if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
        with:
          name: ${{ env.ARCHIVE_NAME }}
          path: ${{ env.ARCHIVE_NAME }}.zip

  build-macos-arm64:
    runs-on: macos-14
    env:
      ARCHIVE_NAME: ${{ github.event.repository.name }}-${{ github.event.release.tag_name || 'nightly' }}-macos-arm64
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: 'mac'
          target: 'desktop'
          arch: 'clang_64'
          modules: 'qt5compat qtpositioning qtwebchannel qtwebengine'
          cache: 'true'
          cache-key-prefix: 'install-qt-action-macos_clang_arm64'

      - name: Configure
        env:
          NIGHTLY_BUILD: ${{ inputs.nightly || github.event_name != 'release' }}
          RELEASE_VERSION: ${{ inputs.version || github.event.release.tag_name }}
        run: |
          mkdir build
          if ${{ env.NIGHTLY_BUILD }} ; then
            cmake -DNIGHTLY_BUILD=ON -DQT_DEBUG_FIND_PACKAGE=ON -DGIT_HASH=$(git rev-parse --short=7 HEAD) -DCMAKE_OSX_ARCHITECTURES="arm64" -S . -B build
          else
            VER=${{ env.RELEASE_VERSION }}
            cmake -DNIGHTLY_BUILD=OFF -DREL_VER=${VER#v} -DCMAKE_OSX_ARCHITECTURES="arm64" -S . -B build
          fi

      - name: Build
        run: |
          cmake --build build --target ${{ env.TARGET_NAME }} --parallel $(nproc)

      - name: Download and copy files
        run: |
          cp -R build/${{ env.TARGET_NAME }}.app .
          curl -LO https://github.com/chenx-dust/zju-connect/releases/latest/download/zju-connect-darwin-arm64.zip
          tar -xf zju-connect-darwin-arm64.zip
          rm zju-connect-darwin-arm64.zip
          cp zju-connect ${{ env.TARGET_NAME }}.app/Contents/MacOS/
          macdeployqt ${{ env.TARGET_NAME }}.app

      - name: Package dmg file
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        run: |
          brew install create-dmg
          mkdir dmg-build
          create-dmg \
            --background ./resource/dmg-background.png \
            --window-size 430 480 \
            --app-drop-link 200 0 \
            --add-file "${{ env.DISPLAY_NAME }}.app" "./${{ env.TARGET_NAME }}.app" 0 0 \
            --add-file 修复脚本.command ./resource/macos-fix.sh 100 200 \
            --filesystem APFS \
            ${{ env.ARCHIVE_NAME }}.dmg dmg-build

      - name: Upload artifact (dmg)
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARCHIVE_NAME }}
          path: ${{ env.ARCHIVE_NAME }}.dmg

      - name: Package zip file
        if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
        run: |
          zip -r ${{ env.ARCHIVE_NAME }}.zip ${{ env.TARGET_NAME }}.app

      - name: Upload artifact (zip)
        uses: actions/upload-artifact@v4
        if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
        with:
          name: ${{ env.ARCHIVE_NAME }}
          path: ${{ env.ARCHIVE_NAME }}.zip

  build-linux-x64:
    runs-on: ubuntu-22.04
    env:
      ARCHIVE_NAME: ${{ github.event.repository.name }}-${{ github.event.release.tag_name || 'nightly' }}-linux-x64
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: 'linux'
          target: 'desktop'
          arch: 'linux_gcc_64'
          modules: 'qt5compat qtpositioning qtserialport qtwebchannel qtwebengine'
          cache: 'true'
          cache-key-prefix: 'install-qt-action-linux_gcc_64'

      - name: Configure
        env:
          NIGHTLY_BUILD: ${{ inputs.nightly || github.event_name != 'release' }}
          RELEASE_VERSION: ${{ inputs.version || github.event.release.tag_name }}
        run: |
          mkdir build
          if ${{ env.NIGHTLY_BUILD }} ; then
            cmake -DNIGHTLY_BUILD=ON -DQT_DEBUG_FIND_PACKAGE=ON -DGIT_HASH=$(git rev-parse --short=7 HEAD) -S . -B build
          else
            VER=${{ env.RELEASE_VERSION }}
            cmake -DNIGHTLY_BUILD=OFF -DREL_VER=${VER#v} -S . -B build
          fi

      - name: Build
        run: |
          cmake --build build --target ${{ env.TARGET_NAME }} --parallel $(nproc)

      - name: Download and copy files
        run: |
          sudo apt install -y libxcb-cursor0 fuse

          wget -O linuxdeploy https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          wget -O linuxdeploy-plugin-qt https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
          chmod a+x linuxdeploy linuxdeploy-plugin-qt

          mkdir AppDir
          mkdir -p AppDir/usr/bin AppDir/usr/lib AppDir/usr/share/applications AppDir/usr/share/icons/hicolor/scalable/apps

          cp build/${{ env.TARGET_NAME }} AppDir/usr/bin/
          wget -O zju-connect-linux-amd64.zip https://github.com/chenx-dust/zju-connect/releases/latest/download/zju-connect-linux-amd64.zip
          unzip zju-connect-linux-amd64.zip
          cp zju-connect AppDir/usr/bin/
          cp resource/icon.png AppDir/usr/share/icons/hicolor/scalable/apps/${{ env.TARGET_NAME }}.png

          cat <<EOF > AppDir/usr/share/applications/${{ env.TARGET_NAME }}.desktop
          [Desktop Entry]
          Name=${{ env.DISPLAY_NAME }}
          Exec=${{ env.TARGET_NAME }}
          Icon=${{ env.TARGET_NAME }}
          Type=Application
          Categories=Network;Security;
          EOF

          ./linuxdeploy --appdir AppDir --output appimage --plugin qt
          mv *.AppImage ${{ env.ARCHIVE_NAME }}.AppImage

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARCHIVE_NAME }}
          path: ${{ env.ARCHIVE_NAME }}.AppImage

  build-linux-arm64:
    runs-on: ubuntu-24.04-arm
    env:
      ARCHIVE_NAME: ${{ github.event.repository.name }}-${{ github.event.release.tag_name || 'nightly' }}-linux-arm64
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libevent-2.1-7t64 libminizip1t64

      - name: Install Qt
        uses: jdpurcell/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: 'linux_arm64'
          target: 'desktop'
          arch: 'linux_gcc_arm64'
          modules: 'qt5compat qtpositioning qtserialport qtwebchannel qtwebengine'
          cache: 'true'
          cache-key-prefix: 'install-qt-action-linux_arm64'

      - name: Configure
        env:
          NIGHTLY_BUILD: ${{ inputs.nightly || github.event_name != 'release' }}
          RELEASE_VERSION: ${{ inputs.version || github.event.release.tag_name }}
        run: |
          mkdir build
          if ${{ env.NIGHTLY_BUILD }} ; then
            cmake -DNIGHTLY_BUILD=ON -DQT_DEBUG_FIND_PACKAGE=ON -DGIT_HASH=$(git rev-parse --short=7 HEAD) -S . -B build
          else
            VER=${{ env.RELEASE_VERSION }}
            cmake -DNIGHTLY_BUILD=OFF -DREL_VER=${VER#v} -S . -B build
          fi

      - name: Build
        run: |
          cmake --build build --target ${{ env.TARGET_NAME }} --parallel $(nproc)

      - name: Download and copy files
        run: |
          sudo apt install -y libxcb-cursor0 fuse

          wget -O linuxdeploy https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-aarch64.AppImage
          wget -O linuxdeploy-plugin-qt https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-aarch64.AppImage
          chmod a+x linuxdeploy linuxdeploy-plugin-qt

          mkdir AppDir
          mkdir -p AppDir/usr/bin AppDir/usr/lib AppDir/usr/share/applications AppDir/usr/share/icons/hicolor/scalable/apps

          cp build/${{ env.TARGET_NAME }} AppDir/usr/bin/
          wget -O zju-connect-linux-arm64.zip https://github.com/chenx-dust/zju-connect/releases/latest/download/zju-connect-linux-arm64.zip
          unzip zju-connect-linux-arm64.zip
          cp zju-connect AppDir/usr/bin/
          cp resource/icon.png AppDir/usr/share/icons/hicolor/scalable/apps/${{ env.TARGET_NAME }}.png

          cat <<EOF > AppDir/usr/share/applications/${{ env.TARGET_NAME }}.desktop
          [Desktop Entry]
          Name=${{ env.DISPLAY_NAME }}
          Exec=${{ env.TARGET_NAME }}
          Icon=${{ env.TARGET_NAME }}
          Type=Application
          Categories=Network;Security;
          EOF

          ./linuxdeploy --appdir AppDir --output appimage --plugin qt
          mv *.AppImage ${{ env.ARCHIVE_NAME }}.AppImage

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARCHIVE_NAME }}
          path: ${{ env.ARCHIVE_NAME }}.AppImage

  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    needs:
      - build-windows-x64
      - build-windows-arm64
      - build-macos-x64
      - build-macos-arm64
      - build-linux-x64
      - build-linux-arm64
    env:
      ARCHIVE_PREFIX: ${{ github.event.repository.name }}-${{ github.event.release.tag_name || 'nightly' }}
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ env.ARCHIVE_PREFIX }}-*
          merge-multiple: true

      - name: Upload to release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} ${{ env.ARCHIVE_PREFIX }}-*
